### ISSUE TITLE
[FE] 1주차 PR 리뷰 반영

### ISSUE THREAD

**Issue by mina-gwak** [CODESQUAD-AIRBNB/airbnb#11]
## 💡 description

PR에서 리뷰받은 내용들을 반영하여 수정한다.

## 📝 todo
- 1번째 PR
- [x] `Prettier` 설정 변경, 함수 반환값 형식 변경
- [x] `prop-types` 등 사용하지 않는 플러그인/라이브러리 삭제
- [x] dependencies => devDependencies 로 변경할 내용 확인
- [ ] 글로벌 스타일 출처 찾기..
- [x] export 방식 변경 (모아서 하는 방식 => 각각 내보내는 방식)
- 2번째 PR
- [x]  constants.tsx ⇒ ts로 변경
- [x]  Header/index에서 index 제외
- [x]  푸터에 있는 constants파일 datas폴더로 옮기기
- [x]  type ⇒ interface로 변경
