### ISSUE TITLE
[FE] Header, 메인 컨텐츠 일부 생성

### ISSUE THREAD

**Issue by mina-gwak** [CODESQUAD-AIRBNB/airbnb#12]
## 💡 description

Header와 메인 컨텐츠 중 `가까운 여행지 둘러보기` 부분을 만든다.

## 📝 todo
- [x] 기존의 Header => GNB로 변경
- [x] Header 컴포넌트 생성
- [x] 메인 컨텐츠 영역 생성
