### ISSUE TITLE
[BE] airbnb 프로젝트 PR #2 리뷰 반영

### ISSUE THREAD

**Issue by dongkyu-park** [CODESQUAD-AIRBNB/airbnb#14]
## 💡 description
2번째 PR 리뷰 받은 내용 반영

## 📝 todo
- [x] 재할당하지 않는 필드는 final 키워드로 선언하기
- [x] hibernate ddl auto 설정값들에 대해 학습하고 validate로 적용해보기
- [x] 테이블 생성, 컬럼들의 자료형과 범위 생각해보고 수정하기
