### ISSUE TITLE
[FE] 리팩토링, 모달구현 

### ISSUE THREAD

**Issue by suuzin** [CODESQUAD-AIRBNB/airbnb#15]
## 💡 description
1주차 두번째 리뷰 반영, 모달구현 방법 모색 

## 📝 todo
- [x] Footer 네이밍 개선
- [x] 데이터 가져오기 - MSW 
- [x] Main Content Section 하나로 합치기
- [ ] modal 구현
