### ISSUE TITLE
[BE] airbnb 프로젝트 PR #3 리뷰 반영

### ISSUE THREAD

**Issue by dongkyu-park** [CODESQUAD-AIRBNB/airbnb#26]
## 💡 description
https://github.com/codesquad-members-2022/airbnb/pull/180
코드 개선해보기

## 📝 todo
- [x] object로 선언한 data type을 generic선언으로 변경하기
- [x] 예외 핸들러 Validation 분기 로직 제거 -> Validation의 message설정을 이용하여 처리하게끔 바꾸기
- [x] 하드코딩한 json 문자열 ObjectMapper를 이용하여 변경하기
- [x] 네이티브 쿼리 사용한 부분 개선 고민해보기. 꼭 DB에서 작업을 해야 하는가?
