### ISSUE TITLE
[FE] 프로젝트 초기 설정

### ISSUE THREAD

**Issue by suuzin** [CODESQUAD-AIRBNB/airbnb#3]
## 💡 description
프로젝트 초기 설정

## 📝 todo
- [x] 사용할 라이브러리 정하기
- [x] 절대경로 설정
- [x] import/order 설정
- [x] 타입스크립트 세팅
- [x] PR 템플릿 생성
