### ISSUE TITLE
[FE] 리뷰 반영 & 인원 모달 생성

### ISSUE THREAD

**Issue by mina-gwak** [CODESQUAD-AIRBNB/airbnb#31]
## 💡 description

- 지난 PR에서 받은 리뷰를 반영한다.
- 인원 영역에 뜨는 모달을 생성한다.

## 📝 todo
- [x] pathname 수정
- [x] modal 구조 수정
- [x] 컴포넌트 Props의 타입 네이밍 수정
- [x] 캔버스 관련 함수 개선
- [x] 모달 밖 영역 클릭 시 모달창 닫는 기능 
- [x] 인원 모달 생성
- [x] [스토리 4](https://github.com/CODESQUAD-AIRBNB/airbnb/wiki/%5BFE%5D-%EC%9A%94%EA%B5%AC%EC%82%AC%ED%95%AD-%EB%B6%84%EC%84%9D#%EC%8A%A4%ED%86%A0%EB%A6%AC-4) 참고하여 기능 구현
