### ISSUE TITLE
[BE] airbnb 프로젝트 PR #4 리뷰 반영

### ISSUE THREAD

**Issue by dongkyu-park** [CODESQUAD-AIRBNB/airbnb#32]
## 💡 description
https://github.com/codesquad-members-2022/airbnb/pull/254
코드 개선해보기

## 📝 todo
- [x] DTO에서 필요한 정보가 한 가지 필드(일부) 라면, 객체 자체를 받아서 DTO가 객체의 모든 정보를 알 필요가 없다. 필요한 인자만을 넘겨주기
- [x] if문, 특정 행위 등은 메서드를 통해 명시적으로 분리해주기
- [x] 다른 사람이 코드를 읽었을 때 메서드명을 보고 행위를 이해할 수 있을까? 고민하기
