### ISSUE TITLE
[BE] airbnb 프로젝트 PR #1 리뷰 반영

### ISSUE THREAD

**Issue by dongkyu-park** [CODESQUAD-AIRBNB/airbnb#9]
## 💡 description
리뷰 받은 내용 반영

## 📝 todo
- [x] 무분별한 setter 사용 지양.
- [x] Discount 객체 필드값 추가하기.
- [x] `@OneToMany` 의 fetchType 을 Lazy 로 변경?
